export const FETCH_MOVIE_LIST_LOADING = 'FETCH_MOVIE_LIST_LOADING';
export const FETCH_MOVIE_LIST_SUCCESS = 'FETCH_MOVIE_LIST_SUCCESS';
export const FETCH_MOVIE_LIST_FAIL = 'FETCH_MOVIE_LIST_FAIL';

export const FETCH_MOVIE_DATA_LOADING = 'FETCH_MOVIE_DATA_LOADING';
export const FETCH_MOVIE_DATA_SUCCESS = 'FETCH_MOVIE_DATA_SUCCESS';
export const FETCH_MOVIE_DATA_FAIL = 'FETCH_MOVIE_DATA_FAIL';
